/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */

rootProject.name = "aws-lambda-stream-kotlin"

include("core")

include(":tools:resubmit-events")

include("examples:common-infra")
include("examples:sut:common-app")
include("examples:sut:sut-event-hub")
include("examples:sut:sut-event-hub:app")
include("examples:sut:sut-event-hub:infra")
include("examples:sut:sut-control-service")
include("examples:sut:sut-control-service:app")
include("examples:sut:sut-control-service:infra")
include("examples:sut:sut-shipment-bff")
include("examples:sut:sut-shipment-bff:app")
include("examples:sut:sut-shipment-bff:infra")
include("examples:sut:sut-event-fault-monitor")
include("examples:sut:sut-event-fault-monitor:app")
include("examples:sut:sut-event-fault-monitor:infra")
include("examples:sut:sut-regional-health-check")
include("examples:sut:sut-regional-health-check:app")
include("examples:sut:sut-regional-health-check:infra")
include("examples:sut:integration-test")